//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cupons.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CuponsEntities : DbContext
    {
        public CuponsEntities()
            : base("name=CuponsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCliente> tblCliente { get; set; }
        public virtual DbSet<tblCuponsFiscais> tblCuponsFiscais { get; set; }
        public virtual DbSet<tblCuponsImpressos> tblCuponsImpressos { get; set; }
        public virtual DbSet<tblLojista> tblLojista { get; set; }
        public virtual DbSet<tblUsuarios> tblUsuarios { get; set; }
    }
}
