//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cupons.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCliente
    {
        public long id { get; set; }
        public string Nome { get; set; }
        public string CPF { get; set; }
        public string RG { get; set; }
        public System.DateTime DataNasc { get; set; }
        public Nullable<bool> Ativo { get; set; }
        public string Sexo { get; set; }
        public string FoneFixo { get; set; }
        public string FoneCelular1 { get; set; }
        public string FoneCelular2 { get; set; }
        public string FoneCelular3 { get; set; }
        public string Whatsapp { get; set; }
        public string Email { get; set; }
        public string Facebook { get; set; }
        public string Twitter { get; set; }
        public string Endereco { get; set; }
        public string EnderecoNumero { get; set; }
        public string EnderecoComplemento { get; set; }
        public string Bairro { get; set; }
        public string Cidade { get; set; }
        public string Estado { get; set; }
        public string CEP { get; set; }
        public string Observacao { get; set; }
        //public byte[] Foto { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public string CadastradoPor { get; set; }
        public Nullable<System.DateTime> DataAlteracao { get; set; }
        public string AlteradoPor { get; set; }
    }
}
