//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cupons.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCuponsImpressos
    {
        public long noCupom { get; set; }
        public long idCliente { get; set; }
        public System.DateTime DataHoraImpressao { get; set; }
        public string GeradoPor { get; set; }
        public bool Impresso { get; set; }
    }
}
