//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cupons.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLojista
    {
        public long id { get; set; }
        public string CNPJLojista { get; set; }
        public string IELojista { get; set; }
        public string RazaoLojista { get; set; }
        public string FantasiaLojista { get; set; }
        public bool Ativo { get; set; }
        public Nullable<long> idRamoAtividade { get; set; }
    }
}
